// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dariabarinovakt4120.Database;

#nullable disable

namespace dariabarinovakt4120.Migrations
{
    [DbContext(typeof(SubjectDbContext))]
    partial class SubjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dariabarinovakt4120.Models.Direction", b =>
                {
                    b.Property<int>("DirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("direction_id")
                        .HasComment("ID направления");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectionId"));

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("direction_name")
                        .HasComment("Название направления");

                    b.HasKey("DirectionId")
                        .HasName("pk_direction_direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("dariabarinovakt4120.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id")
                        .HasComment("ID предмета");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("DirectionId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("direction_id")
                        .HasComment("ID направления");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted")
                        .HasComment("Статус удаления");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("sudject_name")
                        .HasComment("Название предмета");

                    b.HasKey("SubjectId")
                        .HasName("pk_subject_subject_id");

                    b.HasIndex(new[] { "DirectionId" }, "idx_subject_fk_f_direction_id");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("dariabarinovakt4120.Models.Subject", b =>
                {
                    b.HasOne("dariabarinovakt4120.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_direction_id");

                    b.Navigation("Direction");
                });
#pragma warning restore 612, 618
        }
    }
}
